### ISSUE TITLE
Unable to setup krustlet on kubernetes v1.23 

### ISSUE THREAD

**Issue by 3siksfather** [krustlet/krustlet#721] opened 2022-04-29 05:30 UTC
hello.
I wanted to try adding a krustlet node to kubernetes .

Create bootstrap config
```
curl https://raw.githubusercontent.com/krustlet/krustlet/main/scripts/bootstrap.sh | /bin/bash

secret/bootstrap-token-x0h5fb created
Switched to context "kubernetes-admin@cluster.local".
Context "kubernetes-admin@cluster.local" renamed to "tls-bootstrap-token-user@kubernetes".
User "tls-bootstrap-token-user" set.
Context "tls-bootstrap-token-user@kubernetes" modified.
Context "tls-bootstrap-token-user@kubernetes" modified.

```

Download Krustlet
```
curl -O https://krustlet.blob.core.windows.net/releases/krustlet-v1.0.0-alpha.1-linux-amd64.tar.gz
tar -xzf krustlet-v1.0.0-alpha.1-linux-amd64.tar.gz
```
Install Krustlet
```
KUBECONFIG=~/.krustlet/config/kubeconfig \                           
  ./krustlet-wasi \                     
  --node-ip=127.0.0.1 \
  --node-name=krustlet \
  --bootstrap-file=${HOME}/.krustlet/config/bootstrap.conf
```

But I got 
```
$ KUBECONFIG=~/.krustlet/config/kubeconfig \
>   ./krustlet-wasi \
>   --node-ip=127.0.0.1 \
>   --node-name=krustlet \
>   --bootstrap-file=${HOME}/.krustlet/config/bootstrap.conf
Error: ApiError: the server could not find the requested resource: NotFound (ErrorResponse { status: "Failure", message: "the server could not find the requested resource", reason: "NotFound", code: 404 })

Caused by:
    the server could not find the requested resource: NotFound
```

Did I miss something or is kubernetes not supported?

**Comment by numso** [comment] 2022-05-02 21:32
I ran into this issue and was able to solve it by following the advice here and using a canary version of krustlet: https://github.com/krustlet/krustlet/issues/699#issuecomment-968140496.

**Comment by bacongobbler** [comment] 2022-05-02 21:35
Thanks @numso! Closing as a duplicate of #699.

**Closed by bacongobbler** 2022-05-02 21:35 UTC

**Comment by 3siksfather** [comment] 2022-05-03 02:54
@numso 
I've seen this solved with From Canary Builds.
thank you.
